version: '3.8'

services:
  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: dev-password
    volumes:
      - minio_data:/data
    networks:
      - app_network

  # BFF
  bff:
    build: ./bff   # Dockerfile があるディレクトリ
    container_name: bff
    ports:
      - "8080:8080"
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_USER: minio
      MINIO_PASSWORD: dev-password
    networks:
      - app_network

  # PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Backend
  backend:
    build: ./backend   # Dockerfile があるディレクトリ
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - minio
      - db
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_USER: minio
      MINIO_PASSWORD: dev-password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: dev-password
      DATABASE_NAME: mydatabase
    networks:
      - app_network

volumes:
  minio_data:
  db_data:

networks:
  app_network:
    driver: bridge
